// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTwo;

namespace TaskTwo.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskTwo.Models.MasterPage", b =>
                {
                    b.Property<int>("MasterPageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LastDayProfit")
                        .HasColumnType("int");

                    b.Property<int>("LastDayQtySold")
                        .HasColumnType("int");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("int");

                    b.HasKey("MasterPageID");

                    b.ToTable("masterPages");

                    b.HasData(
                        new
                        {
                            MasterPageID = 1,
                            LastDayProfit = 100,
                            LastDayQtySold = 110000,
                            TotalProducts = 0
                        },
                        new
                        {
                            MasterPageID = 2,
                            LastDayProfit = 200,
                            LastDayQtySold = 220000,
                            TotalProducts = 0
                        },
                        new
                        {
                            MasterPageID = 3,
                            LastDayProfit = 3000,
                            LastDayQtySold = 50,
                            TotalProducts = 0
                        });
                });

            modelBuilder.Entity("TaskTwo.Models.TransactionPage", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Asin")
                        .HasColumnType("int");

                    b.Property<int>("LastDayProfit")
                        .HasColumnType("int");

                    b.Property<int>("LastDayQtySold")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MasterPageID")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("MasterPageID");

                    b.ToTable("transactionPages");

                    b.HasData(
                        new
                        {
                            TransactionID = 1,
                            Asin = 10102,
                            LastDayProfit = 110000,
                            LastDayQtySold = 100,
                            LastUpdateDate = new DateTime(1, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MasterPageID = 1,
                            Price = 10000,
                            ProductName = "Pizza"
                        },
                        new
                        {
                            TransactionID = 2,
                            Asin = 200001,
                            LastDayProfit = 220000,
                            LastDayQtySold = 200,
                            LastUpdateDate = new DateTime(1, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MasterPageID = 2,
                            Price = 100,
                            ProductName = "Sauce"
                        },
                        new
                        {
                            TransactionID = 3,
                            Asin = 10102,
                            LastDayProfit = 30000,
                            LastDayQtySold = 50,
                            LastUpdateDate = new DateTime(1, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MasterPageID = 3,
                            Price = 1000,
                            ProductName = "Tamales"
                        });
                });

            modelBuilder.Entity("TaskTwo.Models.TransactionPage", b =>
                {
                    b.HasOne("TaskTwo.Models.MasterPage", "MasterPage")
                        .WithMany("TransactionPages")
                        .HasForeignKey("MasterPageID");
                });
#pragma warning restore 612, 618
        }
    }
}
